name: Deploy and Test Application

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.9'                     # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    # Install dependencies
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack curl

    # Set up Minikube
    - name: Start Minikube
      uses: manusa/actions-setup-minikube@v2
      with:
        minikube version: 'v1.30.1'
        kubernetes version: 'v1.26.3'
        driver: docker

    # Deploy the Helm chart
    - name: Deploy Helm Chart
      run: |
        helm install cat-fact-app ./chart

    # Wait for application to be ready
    - name: Wait for Pods
      run: |
        kubectl wait --for=condition=ready pod -l app=cat-fact-app --timeout=90s

    # Run Tests on REST API
    - name: Test REST API Endpoints
      shell: bash
      run: |
        POD_IP=$(kubectl get pod -l app=cat-fact-app -o jsonpath="{.items[0].status.podIP}")
        echo "Pod IP: $POD_IP"
        curl -f http://$POD_IP:80/fact || exit 1
        curl -f http://$POD_IP:80/health || exit 1
