name: Deploy and Test Application

on:
  push:
    branches: ["main"]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    # Install dependencies
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack curl

    # Set up Minikube
    - name: Start Minikube
      uses: manusa/actions-setup-minikube@v2.13.0
      with:
        minikube version: 'v1.30.1'
        kubernetes version: 'v1.26.3'
        driver: docker

    # Add catfacts.local to Hosts
    - name: Add catfacts.local to Hosts
      run: echo "$(minikube ip) catfacts.local" | sudo tee -a /etc/hosts

    # Deploy the Helm Chart
    - name: Deploy Helm Chart
      run: |
        helm install cat-fact-app ./chart

    # Test REST API Endpoints
    - name: Test REST API Endpoints
      run: |
        minikube service list
        minikube service cat-fact-service --url
        echo "------------------opening the service------------------"
        curl $(minikube service cat-fact-service --url) 
    # SVC_PORT=$(kubectl get svc cat-fact-service -o=jsonpath='{.spec.ports[0].nodePort}')
    # SITE=$(minikube ip)
    # curl -f https://google.com/
    # curl -f http://$SITE:$SVC_PORT/
    # curl -f http://$SITE:$SVC_PORT/health
