name: Deploy and Test Application

on:
  push:
    branches: ["main"]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    # Install dependencies
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack curl

    # Set up Minikube
    - name: Start Minikube
      uses: manusa/actions-setup-minikube@v2.13.0
      with:
        minikube version: 'v1.30.1'
        kubernetes version: 'v1.26.3'
        driver: docker

    # Deploy the Helm chart
    - name: Deploy Helm Chart
      run: |
        helm install cat-fact-app ./chart

    # Run Tests on REST API
    - name: Test REST API Endpoints
      shell: bash
      run: |
        POD_IP=$(kubectl get pod -l app=cat-fact-app -o jsonpath="{.items[0].status.podIP}")
        echo "Pod IP: $POD_IP"
        curl -f http://$POD_IP:80/ || exit 1
        curl -f http://$POD_IP:80/health || exit 1
